set(CPACK_PACKAGE_NAME "Cappy")
set(CPACK_PACKAGE_VENDOR "Cappy Project")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Lightweight screenshot and pinning tool")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Cappy")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_MONOLITHIC_INSTALL ON)

if(WIN32)
    set(CPACK_GENERATOR "NSIS;ZIP")
    set(CPACK_NSIS_DISPLAY_NAME "Cappy")
    set(CPACK_NSIS_PACKAGE_NAME "Cappy")
    set(CPACK_NSIS_MUI_ICON_CODE "")
elseif(UNIX AND NOT APPLE)
    set(CPACK_GENERATOR "DEB;TGZ")
    set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Cappy Project")
    set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt6core6 (>= 6.4), libqt6gui6 (>= 6.4), libqt6widgets6 (>= 6.4)")
    set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "tesseract-ocr, tesseract-ocr-eng, tesseract-ocr-chi-sim")
    set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/XMuli/SunnyCapturer")
    set(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/resources/linux/cappy.svg")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    set(CPACK_PACKAGE_EXECUTABLES "cappy;Cappy")
endif()
