#include "ShellTheme.h"

namespace {

QString lightMainWindowStyleSheet() {
    return QStringLiteral(
        "QMainWindow { background: #e7edf3; color: #13202c; }"
        "QFrame#sectionSurface {"
        "  background: #f9fbfd;"
        "  border: 1px solid #bcc8d4;"
        "  border-radius: 6px;"
        "}"
        "QLabel#sectionTitleLabel { color: #13202c; font-weight: 600; }"
        "QLabel#mutedLabel { color: #485868; }"
        "QLabel#statusLabel {"
        "  color: #173247;"
        "  background: #dce8f3;"
        "  border: 1px solid #b4c6d7;"
        "  border-radius: 6px;"
        "  padding: 8px 10px;"
        "}"
        "QLabel#previewSurface {"
        "  background: #0f1419;"
        "  color: #b7c0c8;"
        "  border: 1px solid #273442;"
        "  border-radius: 6px;"
        "}"
        "QListWidget {"
        "  background: #f9fbfd;"
        "  color: #13202c;"
        "  border: 0;"
        "  outline: none;"
        "}"
        "QListWidget::item {"
        "  background: #f1f5f9;"
        "  border: 1px solid #d2dbe4;"
        "  border-radius: 4px;"
        "  padding: 6px;"
        "  margin: 1px 0;"
        "}"
        "QListWidget::item:hover { background: #e8eef5; }"
        "QListWidget::item:selected {"
        "  background: #dcecff;"
        "  color: #0f1720;"
        "  border-color: #97bbef;"
        "}"
        "QToolButton, QPushButton {"
        "  color: #13202c;"
        "  border: 1px solid #b7c4d0;"
        "  background: #e4ebf2;"
        "  border-radius: 6px;"
        "  padding: 6px 10px;"
        "}"
        "QToolButton:hover, QPushButton:hover { background: #d9e4ee; }"
        "QToolButton:pressed, QPushButton:pressed { background: #ccd9e5; }"
        "QToolButton:disabled, QPushButton:disabled {"
        "  color: #7a8794;"
        "  background: #eef2f6;"
        "  border-color: #d5dde5;"
        "}"
        "QToolButton[accent='true'] {"
        "  color: #0f2b44;"
        "  background: #d6e7fb;"
        "  border-color: #8fb7e6;"
        "}"
        "QToolButton::menu-indicator { image: none; width: 0px; }"
    );
}

QString darkMainWindowStyleSheet() {
    return QStringLiteral(
        "QMainWindow { background: #11161b; color: #e7edf3; }"
        "QFrame#sectionSurface {"
        "  background: #182028;"
        "  border: 1px solid #2d3a46;"
        "  border-radius: 6px;"
        "}"
        "QLabel#sectionTitleLabel { color: #eef4f9; font-weight: 600; }"
        "QLabel#mutedLabel { color: #96a7b7; }"
        "QLabel#statusLabel {"
        "  color: #d9e8f7;"
        "  background: #213447;"
        "  border: 1px solid #35516c;"
        "  border-radius: 6px;"
        "  padding: 8px 10px;"
        "}"
        "QLabel#previewSurface {"
        "  background: #090c10;"
        "  color: #95a2ad;"
        "  border: 1px solid #273442;"
        "  border-radius: 6px;"
        "}"
        "QListWidget {"
        "  background: #182028;"
        "  color: #e7edf3;"
        "  border: 0;"
        "  outline: none;"
        "}"
        "QListWidget::item {"
        "  background: #202a33;"
        "  border: 1px solid #2d3945;"
        "  border-radius: 4px;"
        "  padding: 6px;"
        "  margin: 1px 0;"
        "}"
        "QListWidget::item:hover { background: #26313c; }"
        "QListWidget::item:selected {"
        "  background: #244566;"
        "  color: #f5f9fd;"
        "  border-color: #4e89bf;"
        "}"
        "QToolButton, QPushButton {"
        "  color: #e7edf3;"
        "  border: 1px solid #31404d;"
        "  background: #202a33;"
        "  border-radius: 6px;"
        "  padding: 6px 10px;"
        "}"
        "QToolButton:hover, QPushButton:hover { background: #26323d; }"
        "QToolButton:pressed, QPushButton:pressed { background: #2e3c49; }"
        "QToolButton:disabled, QPushButton:disabled {"
        "  color: #6f7f8e;"
        "  background: #182028;"
        "  border-color: #25313c;"
        "}"
        "QToolButton[accent='true'] {"
        "  color: #eef6ff;"
        "  background: #2d5a86;"
        "  border-color: #4a81b8;"
        "}"
        "QToolButton::menu-indicator { image: none; width: 0px; }"
    );
}

QString lightSettingsDialogStyleSheet() {
    return QStringLiteral(
        "QDialog { background: #e7edf3; color: #13202c; }"
        "QLabel#settingsTitleLabel { color: #13202c; font-weight: 700; }"
        "QLabel#settingsPageTitle { color: #13202c; font-weight: 700; font-size: 18px; }"
        "QWidget#settingsPage, QWidget#settingsScrollContent { background: transparent; }"
        "QScrollArea#settingsScrollArea {"
        "  background: transparent;"
        "  border: 0;"
        "}"
        "QListWidget#settingsNavigation {"
        "  background: transparent;"
        "  border: 0;"
        "  outline: none;"
        "}"
        "QListWidget#settingsNavigation::item {"
        "  background: #f8fbfd;"
        "  color: #1f2f3d;"
        "  border: 1px solid #c1ceda;"
        "  border-radius: 8px;"
        "  padding: 10px 14px;"
        "  margin: 0 0 4px 0;"
        "}"
        "QListWidget#settingsNavigation::item:selected {"
        "  background: #e8f1fb;"
        "  color: #13202c;"
        "  border-color: #7ba7d8;"
        "  font-weight: 600;"
        "}"
        "QListWidget#settingsNavigation::item:hover:!selected {"
        "  background: #eef4f9;"
        "  border-color: #b0c1d1;"
        "}"
        "QStackedWidget#settingsPageStack { background: transparent; }"
        "QFrame#settingsPanel {"
        "  background: #f9fbfd;"
        "  border: 1px solid #bcc8d4;"
        "  border-radius: 10px;"
        "}"
        "QLabel#settingsPanelTitle { font-weight: 600; color: #13202c; }"
        "QLabel#settingsFieldLabel { color: #13202c; font-weight: 500; }"
        "QLabel#settingsValueLabel { color: #485868; }"
        "QCheckBox { color: #13202c; spacing: 8px; }"
        "QCheckBox::indicator {"
        "  width: 16px;"
        "  height: 16px;"
        "  border: 1px solid #aab9c7;"
        "  border-radius: 4px;"
        "  background: #fdfefe;"
        "}"
        "QCheckBox::indicator:checked {"
        "  background: #3b7fbb;"
        "  border-color: #3b7fbb;"
        "}"
        "QScrollBar:vertical {"
        "  width: 12px;"
        "  background: #dbe4ec;"
        "  margin: 0;"
        "  border-radius: 6px;"
        "}"
        "QScrollBar::handle:vertical {"
        "  background: #9fb1c2;"
        "  min-height: 32px;"
        "  border-radius: 6px;"
        "}"
        "QScrollBar::handle:vertical:hover { background: #8ea4b8; }"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,"
        "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {"
        "  height: 0;"
        "  background: transparent;"
        "}"
        "QLineEdit, QComboBox, QKeySequenceEdit, QSpinBox, QPlainTextEdit {"
        "  min-height: 32px;"
        "  color: #13202c;"
        "  border: 1px solid #b7c4d0;"
        "  border-radius: 6px;"
        "  padding: 0 10px;"
        "  background: #fdfefe;"
        "  selection-background-color: #d8eafc;"
        "  selection-color: #0f2940;"
        "}"
        "QPlainTextEdit {"
        "  min-height: 88px;"
        "  padding: 8px 10px;"
        "}"
        "QKeySequenceEdit:focus, QKeySequenceEdit[recording='true'] {"
        "  border: 2px solid #4f91d0;"
        "  padding: 0 9px;"
        "  background: #edf6ff;"
        "  color: #0e3557;"
        "}"
        "QLineEdit:disabled, QComboBox:disabled, QKeySequenceEdit:disabled, QSpinBox:disabled, QPlainTextEdit:disabled {"
        "  color: #718190;"
        "  border-color: #d1dbe4;"
        "  background: #edf2f6;"
        "}"
        "QComboBox QAbstractItemView {"
        "  color: #13202c;"
        "  background: #fdfefe;"
        "  border: 1px solid #b7c4d0;"
        "  selection-background-color: #d8eafc;"
        "  selection-color: #0f2940;"
        "  outline: none;"
        "}"
        "QComboBox::drop-down, QSpinBox::up-button, QSpinBox::down-button { border: 0; }"
        "QPushButton {"
        "  min-height: 32px;"
        "  min-width: 92px;"
        "  color: #13202c;"
        "  border: 1px solid #b7c4d0;"
        "  border-radius: 6px;"
        "  padding: 0 12px;"
        "  background: #e4ebf2;"
        "}"
        "QPushButton:hover { background: #d9e4ee; }"
        "QPushButton:pressed { background: #ccd9e5; }"
        "QPushButton:disabled { color: #7a8794; background: #eef2f6; border-color: #d5dde5; }"
    );
}

QString darkSettingsDialogStyleSheet() {
    return QStringLiteral(
        "QDialog { background: #11161b; color: #e7edf3; }"
        "QLabel#settingsTitleLabel { color: #eef4f9; font-weight: 700; }"
        "QLabel#settingsPageTitle { color: #eef4f9; font-weight: 700; font-size: 18px; }"
        "QWidget#settingsPage, QWidget#settingsScrollContent { background: transparent; }"
        "QScrollArea#settingsScrollArea {"
        "  background: transparent;"
        "  border: 0;"
        "}"
        "QListWidget#settingsNavigation {"
        "  background: transparent;"
        "  border: 0;"
        "  outline: none;"
        "}"
        "QListWidget#settingsNavigation::item {"
        "  background: #1c252e;"
        "  color: #d3dde6;"
        "  border: 1px solid #2d3a46;"
        "  border-radius: 8px;"
        "  padding: 10px 14px;"
        "  margin: 0 0 4px 0;"
        "}"
        "QListWidget#settingsNavigation::item:selected {"
        "  background: #243a50;"
        "  color: #eef4f9;"
        "  border-color: #4b84b8;"
        "  font-weight: 600;"
        "}"
        "QListWidget#settingsNavigation::item:hover:!selected {"
        "  background: #222d37;"
        "  border-color: #3b4a57;"
        "}"
        "QStackedWidget#settingsPageStack { background: transparent; }"
        "QFrame#settingsPanel {"
        "  background: #182028;"
        "  border: 1px solid #2d3a46;"
        "  border-radius: 10px;"
        "}"
        "QLabel#settingsPanelTitle { font-weight: 600; color: #eef4f9; }"
        "QLabel#settingsFieldLabel { color: #d9e3ec; font-weight: 500; }"
        "QLabel#settingsValueLabel { color: #96a7b7; }"
        "QCheckBox { color: #e7edf3; spacing: 8px; }"
        "QCheckBox::indicator {"
        "  width: 16px;"
        "  height: 16px;"
        "  border: 1px solid #4b5b6a;"
        "  border-radius: 4px;"
        "  background: #182028;"
        "}"
        "QCheckBox::indicator:checked {"
        "  background: #4281bb;"
        "  border-color: #4281bb;"
        "}"
        "QScrollBar:vertical {"
        "  width: 12px;"
        "  background: #1a232b;"
        "  margin: 0;"
        "  border-radius: 6px;"
        "}"
        "QScrollBar::handle:vertical {"
        "  background: #415363;"
        "  min-height: 32px;"
        "  border-radius: 6px;"
        "}"
        "QScrollBar::handle:vertical:hover { background: #4c6173; }"
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,"
        "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {"
        "  height: 0;"
        "  background: transparent;"
        "}"
        "QLineEdit, QComboBox, QKeySequenceEdit, QSpinBox, QPlainTextEdit {"
        "  min-height: 32px;"
        "  color: #e7edf3;"
        "  border: 1px solid #31404d;"
        "  border-radius: 6px;"
        "  padding: 0 10px;"
        "  background: #202a33;"
        "  selection-background-color: #2d5a86;"
        "  selection-color: #f4f9ff;"
        "}"
        "QPlainTextEdit {"
        "  min-height: 88px;"
        "  padding: 8px 10px;"
        "}"
        "QKeySequenceEdit:focus, QKeySequenceEdit[recording='true'] {"
        "  border: 2px solid #68a9e2;"
        "  padding: 0 9px;"
        "  background: #263a4d;"
        "  color: #f4f9ff;"
        "}"
        "QLineEdit:disabled, QComboBox:disabled, QKeySequenceEdit:disabled, QSpinBox:disabled, QPlainTextEdit:disabled {"
        "  color: #6f7f8e;"
        "  border-color: #25313c;"
        "  background: #182028;"
        "}"
        "QComboBox QAbstractItemView {"
        "  color: #e7edf3;"
        "  background: #202a33;"
        "  border: 1px solid #31404d;"
        "  selection-background-color: #2d5a86;"
        "  selection-color: #f4f9ff;"
        "  outline: none;"
        "}"
        "QComboBox::drop-down, QSpinBox::up-button, QSpinBox::down-button { border: 0; }"
        "QPushButton {"
        "  min-height: 32px;"
        "  min-width: 92px;"
        "  color: #e7edf3;"
        "  border: 1px solid #31404d;"
        "  border-radius: 6px;"
        "  padding: 0 12px;"
        "  background: #202a33;"
        "}"
        "QPushButton:hover { background: #26323d; }"
        "QPushButton:pressed { background: #2e3c49; }"
        "QPushButton:disabled { color: #6f7f8e; background: #182028; border-color: #25313c; }"
    );
}

}  // namespace

ShellThemeMode shellThemeModeFromSettings(const QString& value) {
    return value.compare("dark", Qt::CaseInsensitive) == 0
        ? ShellThemeMode::Dark
        : ShellThemeMode::Light;
}

QString shellThemeModeToSettingsValue(ShellThemeMode mode) {
    return mode == ShellThemeMode::Dark ? "dark" : "light";
}

QString mainWindowStyleSheetForTheme(ShellThemeMode mode) {
    return mode == ShellThemeMode::Dark
        ? darkMainWindowStyleSheet()
        : lightMainWindowStyleSheet();
}

QString settingsDialogStyleSheetForTheme(ShellThemeMode mode) {
    return mode == ShellThemeMode::Dark
        ? darkSettingsDialogStyleSheet()
        : lightSettingsDialogStyleSheet();
}
